package com.fdmgroup.zorkclone.commands;

public enum Commands {
	AT, ATTACK, BREAK, D, DR, DROP, DON, DOWN, E, EAST, EAT, EQUIP, EX, EXAMINE, FIGHT, G, GET, GO, GRAB, HELP, HIT, I, INVENTORY, K, KILL, L, LOOK, N, NORTH, NORTHWEST, NW, PUSH, PUNCH, PUT, Q, QUIT, REMOVE, S, SAY, SE, SIT, SLEEP, SOUTH, SOUTHEAST, SOUTHWEST, STAB, STAND, SW, STEAL, STRIKE, TAKE, TOUCH, U, UNWIELD, UNEQUIP, UP, W, WAKE, WEAR, WIELD, WEST, X, YELL;

}
